[[SDL2_image]]
arch = "aarch64"
git-tree-sha1 = "5ebb4b9114677f6288d27366c03555cca9d7ab98"
os = "macos"

    [[SDL2_image.download]]
    sha256 = "4a3a42996832fbbb386c23e03c98b2d60edf3cb6721797136ce4eebc4b958f4b"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+1/SDL2_image.v2.6.2.aarch64-apple-darwin.tar.gz"
[[SDL2_image]]
arch = "aarch64"
git-tree-sha1 = "302bc11d6c6c76cc7e96fcff2fe27ead064ae1d0"
libc = "glibc"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "7d3c98c527489a5dc4641027ce7f9fedd0d74014469880a63ba73ec5843187c5"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+1/SDL2_image.v2.6.2.aarch64-linux-gnu.tar.gz"
[[SDL2_image]]
arch = "aarch64"
git-tree-sha1 = "45408b47245d9655882c0aac7a4303c93a63409b"
libc = "musl"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "b1eb4a0dd99802867d688fb1a7eb4661cb6e825a412c8c7331e24bb72ee0bf56"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+1/SDL2_image.v2.6.2.aarch64-linux-musl.tar.gz"
[[SDL2_image]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7100d52bbb9c948bec6cbbc9a8363a8bbab60405"
libc = "glibc"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "df5b4e9b707b03292efe90b8325c9245417e8610c0fb79cd05acdbfd9d8ae067"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+1/SDL2_image.v2.6.2.armv6l-linux-gnueabihf.tar.gz"
[[SDL2_image]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "efa17e5f42fc4757eeb8e44d2e9b150719327133"
libc = "musl"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "12b2fb8fdb3754c2224c55c8274a11891b62c974acbfe525a33c309393f8f155"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+1/SDL2_image.v2.6.2.armv6l-linux-musleabihf.tar.gz"
[[SDL2_image]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "42e4f030c19137c7649f72fbcea020bc62a2a69c"
libc = "glibc"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "c8b7522cd264745da91544393b81aad84d34857f60ada6a7862a04c3dab84305"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+1/SDL2_image.v2.6.2.armv7l-linux-gnueabihf.tar.gz"
[[SDL2_image]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "806ede11fb2435ad84cb490b16f49663ddf4f892"
libc = "musl"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "6153ea5b35190a588cf6f20b36caad21a6eac42c9b0b59d742b39b13972aa6cc"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+1/SDL2_image.v2.6.2.armv7l-linux-musleabihf.tar.gz"
[[SDL2_image]]
arch = "i686"
git-tree-sha1 = "8db92178db808599085778fcb84900e27dbdc1c2"
libc = "glibc"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "fc6c72bd18111bbb1fb52db30703a29ac50f7a7e17f62b1192f850cc23806490"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+1/SDL2_image.v2.6.2.i686-linux-gnu.tar.gz"
[[SDL2_image]]
arch = "i686"
git-tree-sha1 = "c429a14d9381ecb78952d4abbe429b491117b867"
libc = "musl"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "8b31e31cfeaeedffa941a6fe449ad5a08ac781c9b5bfcf0d7a66a765e1474462"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+1/SDL2_image.v2.6.2.i686-linux-musl.tar.gz"
[[SDL2_image]]
arch = "i686"
git-tree-sha1 = "eac99f64afc23f382d070332d5c3154f4df276e7"
os = "windows"

    [[SDL2_image.download]]
    sha256 = "8c04a9c55421ae62f6e09784e254617cf7491717f2b20afc085e7d2705066af4"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+1/SDL2_image.v2.6.2.i686-w64-mingw32.tar.gz"
[[SDL2_image]]
arch = "powerpc64le"
git-tree-sha1 = "4f252e1224e96e88fc68e97588816da012ec4e39"
libc = "glibc"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "d8c9d068739d9dcaa475a197a6057f67a22b74cfded4e0b119fef33b9e3e77bb"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+1/SDL2_image.v2.6.2.powerpc64le-linux-gnu.tar.gz"
[[SDL2_image]]
arch = "x86_64"
git-tree-sha1 = "f7e15929d0977c00ee110a6f857d1d3c9d7161f9"
os = "macos"

    [[SDL2_image.download]]
    sha256 = "765c545369f35c1c4f614c7d88ba7d01bd6477089149c5c9dd638a96f877c49d"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+1/SDL2_image.v2.6.2.x86_64-apple-darwin.tar.gz"
[[SDL2_image]]
arch = "x86_64"
git-tree-sha1 = "b92c5b0d09e5b55e1643dea14662ceef9b50155e"
libc = "glibc"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "2fdbcbeec514d68431696f7d7a425ab0337df83152e5fb46522f904708b5f963"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+1/SDL2_image.v2.6.2.x86_64-linux-gnu.tar.gz"
[[SDL2_image]]
arch = "x86_64"
git-tree-sha1 = "5c9119821950fa209ecb582c58c79b5e9453acf7"
libc = "musl"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "c2045609db1879cdd4f084ceb469cdc655d728636d286386630fc2d9c1487fad"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+1/SDL2_image.v2.6.2.x86_64-linux-musl.tar.gz"
[[SDL2_image]]
arch = "x86_64"
git-tree-sha1 = "f72b9e0c953d247a482f288c218b6fe390104823"
os = "freebsd"

    [[SDL2_image.download]]
    sha256 = "14e8b514e04883a01a81415db1e533e1cd7bf3685854b3e44d70453d61ee029b"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+1/SDL2_image.v2.6.2.x86_64-unknown-freebsd.tar.gz"
[[SDL2_image]]
arch = "x86_64"
git-tree-sha1 = "fa03230282478d82c2295049d440075426a17202"
os = "windows"

    [[SDL2_image.download]]
    sha256 = "a8e349ccaba1f843b15b95761e291ee4806c700571839fcfd57ad9a61d4d8e25"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+1/SDL2_image.v2.6.2.x86_64-w64-mingw32.tar.gz"
