[[SDL2_image]]
arch = "aarch64"
git-tree-sha1 = "373845c7ff7d385260ff6122a761fe796b095eba"
os = "macos"

    [[SDL2_image.download]]
    sha256 = "5f963847d13610baaa45137ab44e39365fb63c07291a36ed11a82c4e908ea61d"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+0/SDL2_image.v2.6.2.aarch64-apple-darwin.tar.gz"
[[SDL2_image]]
arch = "aarch64"
git-tree-sha1 = "0abc065aa4afa3031fcd3608054189f25767c6fd"
libc = "glibc"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "784c6fcd05cb6a0cfe7f6675e617fa52e404a679aa758211c91c65f020a3277a"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+0/SDL2_image.v2.6.2.aarch64-linux-gnu.tar.gz"
[[SDL2_image]]
arch = "aarch64"
git-tree-sha1 = "727a05207a1a1ae1f4f30022e9442c43305d1fe3"
libc = "musl"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "ecd6d7f59b9068442036a5299ec2e3845a01dbb3db04a08e1e84313c48810d3b"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+0/SDL2_image.v2.6.2.aarch64-linux-musl.tar.gz"
[[SDL2_image]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e6f13a14488caefadbd8b7cea0e989348eefaf7"
libc = "glibc"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "5efa6e98195365c4a1291c0aa426a3c603cfd5335b67cc674723496631346bf2"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+0/SDL2_image.v2.6.2.armv6l-linux-gnueabihf.tar.gz"
[[SDL2_image]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "babf93ef2bdd641949df6fc38abd4369f4208e40"
libc = "musl"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "68c44ecfdac5af30cc95f11be72ba50d8c8505e962d1224886fce403cd5245ef"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+0/SDL2_image.v2.6.2.armv6l-linux-musleabihf.tar.gz"
[[SDL2_image]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "435eb0775ffe1af684497fc3ea04a86751416698"
libc = "glibc"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "fbcf7502973f49061aedb63273c460c3aea659660da22ab2fcc39e3af9bc76c1"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+0/SDL2_image.v2.6.2.armv7l-linux-gnueabihf.tar.gz"
[[SDL2_image]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e03e2bcc0b7241f910633d4b362731d1eb699af9"
libc = "musl"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "7c1afb09d26f0bbb1d1b7334e80b511e1117d06379ee16c5826c040f37c638d6"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+0/SDL2_image.v2.6.2.armv7l-linux-musleabihf.tar.gz"
[[SDL2_image]]
arch = "i686"
git-tree-sha1 = "96c88b27df932bd8a54123176e33878f9c24a360"
libc = "glibc"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "c5e9e654b9fb77ed6448b30f8d23c28c4f6703a980e0307800eae591471a1c0f"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+0/SDL2_image.v2.6.2.i686-linux-gnu.tar.gz"
[[SDL2_image]]
arch = "i686"
git-tree-sha1 = "ebf0406e942c1a474be3eae0f99e296b903b913b"
libc = "musl"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "5321bbf1c3b63f70b6fdb8d4a1502f8be38eb281a1739dc236b31c08403a8e05"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+0/SDL2_image.v2.6.2.i686-linux-musl.tar.gz"
[[SDL2_image]]
arch = "i686"
git-tree-sha1 = "a46f2c17877051577973ffb08d3d2403fd9e8829"
os = "windows"

    [[SDL2_image.download]]
    sha256 = "760725f806f668ebe78fbfb160a1935f1d53afc444213a0763799c0f6da56374"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+0/SDL2_image.v2.6.2.i686-w64-mingw32.tar.gz"
[[SDL2_image]]
arch = "powerpc64le"
git-tree-sha1 = "3bd1cc2b9f93a6498174599970150e28080e3f7b"
libc = "glibc"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "a953c5dcf15fde36ce10a2960f5dd2463fbea54ebc6afef4066ed28670cc9384"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+0/SDL2_image.v2.6.2.powerpc64le-linux-gnu.tar.gz"
[[SDL2_image]]
arch = "x86_64"
git-tree-sha1 = "ebc5a9bbb199bcb1a3cf08a266c5b9ec2ccce778"
os = "macos"

    [[SDL2_image.download]]
    sha256 = "d4db3a8199389bf55ef09ab06874c18d4c6bada7f2eb41f926afad417228dfc8"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+0/SDL2_image.v2.6.2.x86_64-apple-darwin.tar.gz"
[[SDL2_image]]
arch = "x86_64"
git-tree-sha1 = "7407000f15b0d117607f4bd58f10687096376fe2"
libc = "glibc"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "787e917f551c3622ada87615604f3ab45b9b4d6582ebb9b0074baf47bddeb4e3"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+0/SDL2_image.v2.6.2.x86_64-linux-gnu.tar.gz"
[[SDL2_image]]
arch = "x86_64"
git-tree-sha1 = "0be0781cce663d96d6fb4ebaacd33d819e7e9df4"
libc = "musl"
os = "linux"

    [[SDL2_image.download]]
    sha256 = "6f1f09c0994dff7bcefba5d6a057b4de93997ded947ade56e8191f2edb8bc67b"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+0/SDL2_image.v2.6.2.x86_64-linux-musl.tar.gz"
[[SDL2_image]]
arch = "x86_64"
git-tree-sha1 = "372343ef147052e6719ce5730fe3b17c8fcf7be5"
os = "freebsd"

    [[SDL2_image.download]]
    sha256 = "b842ada4de10548cc8cc8e2b2e4b2df4d2cc5e1e7c3b85f279c7451a294f7068"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+0/SDL2_image.v2.6.2.x86_64-unknown-freebsd.tar.gz"
[[SDL2_image]]
arch = "x86_64"
git-tree-sha1 = "f732b0010dc112bc07b5f2bd0fe338daa08af7ba"
os = "windows"

    [[SDL2_image.download]]
    sha256 = "9b2433b228f12db8b98ec68ce53f1c069c3c053e2f32588a740dc0e7954f7f5b"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_image_jll.jl/releases/download/SDL2_image-v2.6.2+0/SDL2_image.v2.6.2.x86_64-w64-mingw32.tar.gz"
